# Generated by Django 4.1.4 on 2022-12-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_favorits'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorits',
            constraint=models.UniqueConstraint(fields=('advertisement', 'creator'), name='favorits_unique'),
        ),
    ]
