# Generated by Django 4.1.4 on 2022-12-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_decription_sensor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='temp',
            new_name='temperature',
        ),
    ]
