# Generated by Django 4.1.4 on 2022-12-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_rename_temp_measurement_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
