# Generated by Django 4.1.4 on 2022-12-13 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_rename_sensor_id_measurement_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата измерения'),
        ),
    ]
