# Generated by Django 4.1.4 on 2022-12-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_sensor_name'),
        ),
    ]
