# Generated by Django 4.1.4 on 2022-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_sensor_unique_sensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
