# Generated by Django 4.1.4 on 2022-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_alter_measurement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/img/', verbose_name='Фотография'),
        ),
    ]
